apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-transactions-service
  namespace: eks-transactions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-transactions-service

  template:
    metadata:
      labels:
        app: eks-transactions-service

    spec:
      serviceAccountName: eks-transactions-service

      containers:
        - name: eks-transactions-service
          image: 263953131930.dkr.ecr.af-south-1.amazonaws.com/eks-transactions-service:103cf00dfb62
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          env:
            - name: DB_URL
              value: jdbc:postgresql://eks-transactions-db.cfagqegouk6i.af-south-1.rds.amazonaws.com:5432/transactions

          command:
            - /bin/sh
            - -c

          args:
            - |
              export DB_USER="$(cat /mnt/secrets-store/dbUsername)"
              export DB_PASSWORD="$(cat /mnt/secrets-store/dbPassword)"
              echo "Starting EKS Transaction Service with Amazon RDS..."
              exec catalina.sh run

          volumeMounts:
            - name: rds-secrets
              mountPath: /mnt/secrets-store
              readOnly: true

          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 768Mi

          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
            failureThreshold: 3

      volumes:
        - name: rds-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: eks-transactions-rds-secret

---
apiVersion: v1
kind: Service
metadata:
  name: eks-transactions-service
  namespace: eks-transactions
spec:
  selector:
    app: eks-transactions-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
